### ISSUE TITLE
Downloading aar through dropbox requires me to login to dropbox

### ISSUE THREAD

**Issue by EDDYMENS** [DevlessTeam/dv-android-sdk-1.0#14]

**Comment by charlesagyemang** [comment]
bad idea let me change the method

**Comment by charlesagyemang** [comment]
Whipped up a rails app to one thing and nothing only i.e. host our aar file and make it available for direct download no change of urls just click on the 'here' on the readme and it will call the app on heroku and make it available for download. This should solve the problem for both safari, chrome and break the sign up before download that drop box offered
